name: Build and run tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradle wrapper and run build w/ tests
        run: |
          chmod +x gradlew
          ./gradlew build